In [14]:
import pandas as pd
import sqlalchemy
from sqlalchemy import create_engine

In [2]:
### Extracted CSVs into DataFrames

In [3]:
data_file = "Resources/data.csv"
data_df = pd.read_csv(data_file)
data_df.head()

,valence,year,acousticness,artists,danceability,duration_ms,energy,explicit,id,instrumentalness,key,liveness,loudness,mode,name,popularity,release_date,speechiness,tempo
0,0.0594,1921,0.982,"['Sergei Rachmaninoff', 'James Levine', 'Berli...",0.279,831667,0.211,0,4BJqT0PrAfrxzMOxytFOIz,0.878000,10,0.665,-20.096,1,"Piano Concerto No. 3 in D Minor, Op. 30: III. ...",4,1921,0.0366,80.954
1,0.9630,1921,0.732,['Dennis Day'],0.819,180533,0.341,0,7xPhfUan2yNtyFG0cUWkt8,0.000000,7,0.160,-12.441,1,Clancy Lowered the Boom,5,1921,0.4150,60.936
2,0.0394,1921,0.961,['KHP Kridhamardawa Karaton Ngayogyakarta Hadi...,0.328,500062,0.166,0,1o6I8BglA6ylDMrIELygv1,0.913000,3,0.101,-14.850,1,Gati Bali,5,1921,0.0339,110.339
3,0.1650,1921,0.967,['Frank Parker'],0.275,210000,0.309,0,3ftBPsC5vPBKxYSee08FDH,0.000028,5,0.381,-9.316,1,Danny Boy,3,1921,0.0354,100.109
4,0.2530,1921,0.957,['Phil Regan'],0.418,166693,0.193,0,4d6HGyGT8e121BsdKmw9v6,0.000002,3,0.229,-10.096,1,When Irish Eyes Are Smiling,2,1921,0.0380,101.665

In [4]:
data2_file = "Resources/data2.csv"
data2_df = pd.read_csv(data2_file, dtype='unicode')
data2_df.head()

,Unnamed: 0,uri,rank,artist_names,artists_num,artist_individual,artist_id,artist_genre,artist_img,collab,...,acousticness,instrumentalness,liveness,valence,tempo,duration,country,region,language,pivot
0,0,spotify:track:2gpQi3hbcUAcEG8m2dlgfB,1,Paulo Londra,1.0,Paulo Londra,spotify:artist:3vQ0GE3mI0dAaxIMYe5g7z,argentine hip hop,https://i.scdn.co/image/ab6761610000e5ebf796a9...,0,...,0.0495,0.0,0.0658,0.557,173.935,178203.0,Argentina,South America,Spanish,0
1,1,spotify:track:2x8oBuYaObjqHqgGuIUZ0b,2,WOS,1.0,WOS,spotify:artist:5YCc6xS5Gpj3EkaYGdjyNK,argentine indie,https://i.scdn.co/image/ab6761610000e5eb75e151...,0,...,0.7240000000000001,0.0,0.134,0.262,81.956,183547.0,Argentina,South America,Spanish,0
2,2,spotify:track:2SJZdZ5DLtlRosJ2xHJJJa,3,Paulo Londra,1.0,Paulo Londra,spotify:artist:3vQ0GE3mI0dAaxIMYe5g7z,argentine hip hop,https://i.scdn.co/image/ab6761610000e5ebf796a9...,0,...,0.241,0.0,0.0929,0.21600000000000005,137.915,204003.0,Argentina,South America,Spanish,0
3,3,spotify:track:1O2pcBJGej0pmH2Y9XZMs6,5,Cris Mj,1.0,Cris Mj,spotify:artist:1Yj5Xey7kTwvZla8sqdsdE,urbano chileno,https://i.scdn.co/image/ab6761610000e5eb8f4ebc...,0,...,0.0924,4.6e-05,0.0534,0.8320000000000001,96.018,153750.0,Argentina,South America,Spanish,0
4,4,spotify:track:1TpZKxGnHp37ohJRszTSiq,6,Emilia,1.0,Emilia,spotify:artist:0AqlFI0tz2DsEoJlKSIiT9,pop argentino,https://i.scdn.co/image/ab6761610000e5ebaf96d1...,0,...,0.0811,6.25e-05,0.101,0.501,95.066,133895.0,Argentina,South America,Spanish,0

In [5]:
### Transformed Data CSV DataFrame

In [6]:
data_cols = ["id","valence", "acousticness", "artists", "energy","tempo"]
data_transformed = data_df[data_cols].copy()

data_transformed = data_transformed.rename(columns = {"id": "id","valence":"Valence", "acousticness" :"Acousticness", 
                                                        "artists":"Artists", "energy":"Energy",
                                                         "tempo":"Tempo"})

data_transformed.drop_duplicates("id", inplace = True)
data_transformed.set_index("id", inplace = True)

data_transformed.head()

,Valence,Acousticness,Artists,Energy,Tempo
id,,,,,
4BJqT0PrAfrxzMOxytFOIz,0.0594,0.982,"['Sergei Rachmaninoff', 'James Levine', 'Berli...",0.211,80.954
7xPhfUan2yNtyFG0cUWkt8,0.9630,0.732,['Dennis Day'],0.341,60.936
1o6I8BglA6ylDMrIELygv1,0.0394,0.961,['KHP Kridhamardawa Karaton Ngayogyakarta Hadi...,0.166,110.339
3ftBPsC5vPBKxYSee08FDH,0.1650,0.967,['Frank Parker'],0.309,100.109
4d6HGyGT8e121BsdKmw9v6,0.2530,0.957,['Phil Regan'],0.193,101.665

In [7]:
### Transform Data2 CSV DataFrame

In [8]:
data2_cols = ["artist_id","valence", "acousticness", "artist_names", "liveness","tempo"]


data2_transformed = data2_df[data2_cols].copy()
data2_transformed = data2_transformed.rename(columns = {"artist_id": "id",
                                                        "valence":"Valence", 
                                                        "acousticness" :"Acousticness", 
                                                        "artist_names":"Artists", 
                                                        "liveness":"Energy",
                                                        "tempo":"Tempo"})

data2_transformed.drop_duplicates("id", inplace = True)
data2_transformed.set_index("id", inplace = True)

data2_transformed.head()

,Valence,Acousticness,Artists,Energy,Tempo
id,,,,,
spotify:artist:3vQ0GE3mI0dAaxIMYe5g7z,0.557,0.0495,Paulo Londra,0.0658,173.935
spotify:artist:5YCc6xS5Gpj3EkaYGdjyNK,0.262,0.7240000000000001,WOS,0.134,81.956
spotify:artist:1Yj5Xey7kTwvZla8sqdsdE,0.8320000000000001,0.0924,Cris Mj,0.0534,96.018
spotify:artist:0AqlFI0tz2DsEoJlKSIiT9,0.501,0.0811,Emilia,0.101,95.066
spotify:artist:6KImCVD70vtIoJWnq6nGn3,0.662,0.342,Harry Styles,0.311,173.93

In [9]:
### Created database connection

In [19]:
connection_string = "postgres:postgres@localhost:5432/spotify_db"

engine = create_engine(f'postgresql://{connection_string}')

In [20]:
# Confirm tables
engine.get_table_names()

AttributeError: 'Engine' object has no attribute 'get_table_names'

In [21]:
data_transformed.to_sql(name='data', con=engine, if_exists='append', index=True)

653

In [22]:
data2_transformed.to_sql(name='data2', con=engine, if_exists='append', index=True)

258